# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11, 17 ]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Build with Maven
      run: mvn verify -B -Pcoverage

    - name: Upload coverage report
      if: matrix.java == env.RELEASE_JAVA_VERSION
      uses: codecov/codecov-action@v2
